name: 'Barry Gatlin, Designer'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52146
title: 'Barry Gatlin, Designer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2e513b'
    - '#95817a'
    - '#b41400'
    - '#f42b02'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
