name: 'Barry Gatlin, Designer'
favicon: null
layout_spectrum: 0.49306
typography_spectrum: 0.6678
title: 'Barry Gatlin, Designer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07131f'
    - '#1f3954'
    - '#3a222b'
    - '#3c6b9f'
    - '#743935'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
